name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Run tests (if available)
      run: npm test || echo "No tests configured"

    - name: Create package
      run: npm pack

    - name: Get package info
      id: package
      run: |
        PACKAGE_NAME=$(node -p "JSON.parse(require('fs').readFileSync('package.json', 'utf8')).name")
        PACKAGE_VERSION=$(node -p "JSON.parse(require('fs').readFileSync('package.json', 'utf8')).version")
        # Convert scoped package name to filename format (e.g., @alsoit/frappe-mcp-server -> alsoit-frappe-mcp-server)
        FILENAME=$(echo "$PACKAGE_NAME" | sed 's/@//' | sed 's/\//-/')
        echo "name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
        echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
        echo "filename=${FILENAME}-${PACKAGE_VERSION}.tgz" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## Changes in this Release
          
          ### Features
          - Multi-user authentication support
          - Per-request credential handling
          - Support for multiple Frappe instances
          
          ### Installation
          
          **From GitHub Packages:**
          ```bash
          npm install @alsoit/frappe-mcp-server@${{ steps.package.outputs.version }} --registry=https://npm.pkg.github.com
          ```
          
          **Or install globally:**
          ```bash
          npm install -g @alsoit/frappe-mcp-server@${{ steps.package.outputs.version }} --registry=https://npm.pkg.github.com
          ```
          
          **Or from source:**
          ```bash
          git clone https://github.com/alsoit/frappe-mcp-server.git
          cd frappe-mcp-server
          npm install
          npm run build
          ```
          
          ### Documentation
          - [README](https://github.com/alsoit/frappe-mcp-server#readme)
          - [Multi-User Guide](https://github.com/alsoit/frappe-mcp-server/blob/main/docs/MULTI_USER_GUIDE.md)
          - [Contributing](https://github.com/alsoit/frappe-mcp-server/blob/main/CONTRIBUTING.md)
        files: |
          ${{ steps.package.outputs.filename }}
        draft: false
        prerelease: false

    - name: Publish to GitHub Packages
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    runs-on: ubuntu-latest
    needs: release
    if: success()
    
    steps:
    - name: Notify success
      run: |
        echo "✅ Release completed successfully!"
        echo "📦 Package published to GitHub Packages"
        echo "🚀 GitHub release created" 